#!/bin/bash
#
# @todo Nach jedem Skript Fehler abfangen
#
#

set -e

LSB_RELEASE="/usr/bin/lsb_release"

# Check if we can use colours in our output
use_colour=0
[ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null && use_colour=1

# Some useful functions
progress() {
	[ $use_colour -eq 1 ] && echo -ne "\033[01;32m"
	echo -e "$@" >&2
	[ $use_colour -eq 1 ] && echo -ne "\033[00m"
}

info() {
	[ $use_colour -eq 1 ] && echo -ne "\033[01;34m"
	echo -e "$@" >&2
	[ $use_colour -eq 1 ] && echo -ne "\033[00m"
}

die () {
	[ $use_colour -eq 1 ] && echo -ne "\033[01;31m"
	echo -e "$@" >&2
	[ $use_colour -eq 1 ] && echo -ne "\033[00m"
	exit 1
}

if [ "$1" = "quickinstall" ]
then
    exit_error()
    {
        die "An error occurred while processing quickinstall mode. Pleasy try manually installation"
    }
    trap exit_error EXIT SIGINT SIGTERM
fi

check_install_deb()
{
    progress "Installing dependencies"
    packages=$1
    for P in $packages
    do
        dpkg -s "$P" >/dev/null 2>&1 && {
        info $P is installed
        } || {
            install_package "$P"
        }
    done
}

install_package() {
	package=$1
	info "install ${package}"
	apt-get -qq -y install $package 2>&1 > /dev/null
	return $?
}

[ "x$(id -un)" == "xroot" ] || die "Sorry, this script must be run as root."

[ -x $LSB_RELEASE ] || install_package "lsb-release"

# check architecture
case `dpkg --print-architecture` in
    armhf|arm64)
        info "Found ARM based distribution"
        ;;
    i386|amd64)
        info "X86 CPU found, need to install QEMU"
        check_install_deb "qemu-user-static binfmt-support"
        ;;
    *)
        die "Unsupported CPU architecture, we support only ARM and x86"
        ;;
esac

DIST_ID="$($LSB_RELEASE -is)"
CODENAME="$($LSB_RELEASE -cs)"
DIST=""

# Check the distribution is in the supported list
case "$DIST_ID:$CODENAME" in
Raspbian:jessie) DIST="debian";;
Debian:jessie)	DIST="debian";;
*)		die "Sorry, this script does not support your distribution/release ($DIST_ID $CODENAME)." ;;
esac

progress "Updating sources"
apt-get -q=2 update

progress "Installing dependencies" 
check_install_deb "wget dos2unix python git lxc liblzo2-dev bridge-utils python-lzo patch gzip openssl"

if [ $(cat /etc/profile| grep YAHM | wc -l ) -eq 0 ]
then
    progress "Including YAHM into PATH"
    echo "export PATH=\$PATH:/opt/YAHM/bin" >> /etc/profile 
    export PATH=$PATH:/opt/YAHM/bin
fi

# checkout all files
progress "Downloading all files from repository"
mkdir -p /opt
cd /opt
git clone --recursive https://github.com/leonsio/YAHM.git  2>/dev/null >/dev/null

# create lib folder
mkdir -p /var/lib/yahm

if [ "$1" = "quickinstall" ]
then
    info "\n\tEnter quick install mode\n"

    progress "\tInstalling LXC container"
    /opt/YAHM/bin/yahm-lxc install  2>/dev/null >/dev/null
    info "\tYAHM LXC container was installed successfully\n"

    progress "\tCreating Bridge for networking"
    /opt/YAHM/bin/yahm-network -w create_bridge  2>/dev/null >/dev/null
    info "\tBridge yahmbr0 with interface eth0 was created\n"

    progress "\tAttaching network configuration to LXC container"
    /opt/YAHM/bin/yahm-network attach_bridge  2>/dev/null >/dev/null
    info "\tyahmbr0 was attached to YAHM LXC container\n"

    progress "\tStarting LXC container"
    lxc-start -d yahm -d
    sleep 5
    info "\tYAHM started\n"

    progress "\tDisable Homematic-IP\n"
    /opt/YAHM/bin/yahm-module -f -m homematic-ip disable 2>&1 > /dev/null
    info "\tHomematic-IP was disabled successfully\n"

    info "YAHM was successfully installed, use 'yahm-ctl join' to access YAHM console or 'yahm-ctl show' for IP information"
else
    # Info
    info "Please use yahm-lxc to create new container, yahm-network for network configuration and lxc-enable for additional modules" 
fi
