#!/bin/bash
#
# CuxD
# 

description="CuxD 1.9 for Yahm"

_module_install()
{
 clear
  if (whiptail --yesno --title "CUXd" "Zur Installation muss die CCU neu starten. Fortfahren ? " 20 60) then


  progress "Download ..."
  tmpdest="${YAHM_TMP}/cuxd.tar.gz"
  mkdir -p $YAHM_TMP
    
  cuxdurl="https://homematic-forum.de/forum/download/file.php?id=38158"
  wget -q --tries=3 --retry-connrefused  -O $tmpdest $cuxdurl
    if [ ! -f "$tmpdest" ] 
    then
        die "ERROR: Can not download cuxd. Are you connected to the internet?"
    fi

  progress "Moving ..."
  
  # little roundtrip over opt cause /var is tmp
  mv $tmpdest $LXC_ROOT_FS/opt/new_firmware.tar.gz >/dev/null
  # move it from the inside .. 
  lxc-attach -n ${LXCNAME} -- mv /opt/new_firmware.tar.gz /var/new_firmware.tar.gz  >/dev/null
  progress "running install script ..."

  lxc-attach -n ${LXCNAME} -- /bin/update_firmware_run >/dev/null

  progress "CCU restart ..."
  lxc-attach -n ${LXCNAME} -- /sbin/reboot >/dev/null
  progress "waiting for shutdown ..."

  wait_until_process_isgone ReGaHss
  
  progress "Rega is death Jim !"

  progress "waiting until Rega is back alive .... (cuxd needs 2 boots)"

  wait_for_process ReGaHss
  
  progress "Rega is back ... reboot"
  lxc-attach -n ${LXCNAME} -- /sbin/reboot 

  wait_until_process_isgone ReGaHss

  progress "aaand we are done ..."
  
  return 0
  
  else
   return 1
  fi
}

wait_until_process_isgone() {

  pids=$(pidof $1)
  while kill -0 "$pids" 2>/dev/null
  do
      echo -n "."
      sleep 1
  done
}

wait_for_process() {
  until pids=$(pidof $1)
  do   
   sleep 1
  done
}

_module_remove()
{
  progress "Removing CuxD"
  lxc-attach -n ${LXCNAME} -- /etc/config/rc.d/cuxdaemon uninstall >/dev/null
  lxc-attach -n ${LXCNAME} -- rm -rf /etc/config/rc.d/cuxdaemon >/dev/null
  progress "Done"
}
