#!/bin/bash
#
# CuxD
# 

description="CuxD for Yahm (CCU Restart)"

_module_install()
{

  progress "Download ..."
  tmpdest="${YAHM_TMP}/cuxd.tar.gz"
  mkdir -p $YAHM_TMP
    
  cuxdurl="http://homematic-forum.de/forum/download/file.php?id=31361"
  wget --tries=3 --retry-connrefused  -O $tmpdest $cuxdurl
    if [ ! -f "$tmpdest" ] 
    then
        die "ERROR: Can not download cuxd. Are you connected to the internet?"
    fi

  progress "Moving ..."
  
  # little roundtrip over opt cause /var is tmp
  mv $tmpdest $LXC_ROOT_FS/opt/new_firmware.tar.gz
  # move it from the inside .. 
  lxc-attach -n ${LXCNAME} -- mv /opt/new_firmware.tar.gz /var/new_firmware.tar.gz  
  progress "running install script ..."

  lxc-attach -n ${LXCNAME} -- /bin/update_firmware_run  

  progress "CCU restart ..."
  lxc-attach -n ${LXCNAME} -- /sbin/reboot  
  progress "waiting for shutdown ..."

  pids=$(pidof ReGaHss)
  while kill -0 "$pids"
  do
      echo -n "."
      sleep 1
  done

echo "Rega is gone"

  progress "waiting until Rega is alive .... (cuxd needs 2 boots)"
  until pids=$(pidof ReGaHss)
  do   
   sleep 1
  done
  progress "Rega is alive ... reboot"
  lxc-attach -n ${LXCNAME} -- /sbin/reboot  
  return 0
}

_module_remove()
{
  progress "Removing CuxD"
  lxc-attach -n ${LXCNAME} -- /etc/config/rc.d/cuxdaemon uninstall
  lxc-attach -n ${LXCNAME} -- rm -rf /etc/config/rc.d/cuxdaemon
  progress "Done"
}
