#!/bin/bash
#
# HM-MOD-RPI-PBC 
# 

description="GPIO Funkmodul für Raspberry Pi"

_module_install()
{
    echo "noch nicht fertig"
    exit

    # Host
    # Disable serial
    # @todo

    # enable GPIO output
    echo 18 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio18/direction

    # im Gast

    ln -s /dev/ttyAMA0 /dev/mmd_bidcos
    ln -s /sys/class/gpio/gpio18/value /dev/ccu2-ic200
    mknod -m 666 /dev/ttyAMA0 c 204 64
}

_module_remove()
{
    echo "noch nicht fertig"
    exit
}

