#!/bin/bash

# HM-MOD-RPI Grund konfiguration

# aufm Host

echo out > /sys/class/gpio/gpio18/direction
echo 18 > /sys/class/gpio/export

# im Gast

ln -s /dev/ttyAMA0 /dev/mmd_bidcos
ln -s /sys/class/gpio/gpio18/value /dev/ccu2-ic200
mknod -m 666 /dev/ttyAMA0 c 204 64

