#!/bin/bash
#
# Homematic IP
# 

description="Homematic IP Unterstützung"


_module_install()
{
    echo "noch nicht fertig"
    exit


apt-get install subversion bc gcc-4.7

# aktuelle Kernel Headers runterladen
/opt/YAHM/share/tools/rpi-headers

# Ordner anlegen
mkdir /usr/share/eq3/OCCU
cd /usr/share/eq3/OCCU

# ab git 2.9 koennen wir auch teile auschecken
#git init
#git remote add origin https://github.com/eq-3/occu.git
#git config core.sparsecheckout true
#echo "KernelDrivers/*" >> .git/info/sparse-checkout
#git pull --depth=1 origin master

# nehmen stattdessen svn :D
svn export https://github.com/eq-3/occu/trunk/KernelDrivers

# Makedatei anlegen
cat > "/usr/share/eq3/OCCU/KernelDrivers/Makefile" <<EOF
obj-m	+= eq3_char_loop.c

 
all:
	make -C /lib/modules/\$(shell uname -r)/build M=\$(PWD) modules
 
clean:
	make -C /lib/modules/\$(shell uname -r)/build M=\$(PWD) clean

EOF

# AKtuelle Konfig vorberieten
modprobe configs
# Ins Build verzeichniss wechseln
cd /lib/modules/$(uname -r)/build
gzip -dc /proc/config.gz > .config
# Vorbereitung
make oldconfig


# Modul bauen
cd /usr/share/eq3/OCCU/KernelDrivers/
make clean
insmod eq3_char_loop.ko
}

_module_remove()
{
    check_install_deb "xmlstarlet" 

    progress "Removing HmIP-RF Interface"
    if [ ! -f "${LXC_ROOT_FS}/usr/local/etc/config/InterfacesList.xml" ]
    then
        die "InterfacesList.xml can not be found, please start ${LXCNAME} first"
    fi

    cd ${LXC_ROOT_FS}/usr/local/etc/config/
    xmlstarlet ed -d "/interfaces/ipc[name='HmIP-RF']" InterfacesList.xml > InterfacesList.xml.new
    mv InterfacesList.xml InterfacesList.xml.bak
    mv InterfacesList.xml.new InterfacesList.xml

    cd ${LXC_ROOT_FS}/etc/config_templates/
    xmlstarlet ed -d "/interfaces/ipc[name='HmIP-RF']" InterfacesList.xml > InterfacesList.xml.new
    mv InterfacesList.xml InterfacesList.xml.bak
    mv InterfacesList.xml.new InterfacesList.xml

    progress "Restoring old HMServer.jar file"
    wget $QUIET -O ${LXC_ROOT_FS}/opt/HMServer/HMServer.jar https://raw.githubusercontent.com/eq-3/occu/master/HMserver/opt/HMServer/HMServer.jar
    #Backup old startup file
    mv ${LXC_ROOT_FS}/etc/init.d/S62HMServer ${LXC_ROOT_FS}/etc/init.d/_S62HMServer
    #Create new startup file
    cat > "${LXC_ROOT_FS}/etc/init.d/S61HMServer" <<EOF
#!/bin/sh
#
# Starts HMServer.
#

LOGLEVEL_HMServer=5
CFG_TEMPLATE_DIR=/etc/config_templates

init() {
    export TZ=\`cat /etc/config/TZ | cut -d'-' -f1 | cut -d'+' -f1\`
    export JAVA_HOME=/opt/ejre1.7.0_10/
    export PATH=\$PATH:\$JAVA_HOME/bin
    if [ ! -e /etc/config/log4j.xml ] ; then
        cp \$CFG_TEMPLATE_DIR/log4j.xml /etc/config
    fi
}

start() {
    echo -n "Starting HMServer: "
    init
    start-stop-daemon -S -q -p /var/run/HMServer.pid --exec java -- -Xmx32m -Dlog4j.configuration=file:///etc/config/log4j.xml -Dfile.encoding=ISO-8859-1 -jar /opt/HMServer/HMServer.jar &
    eq3configcmd wait-for-file -f /var/status/HMServerStarted -p 5 -t 135
    echo "OK"
}
stop() {
    echo -n "Stopping HMServer: "
    start-stop-daemon -K -q -p /var/run/HMServer.pid
    echo "OK"
}
restart() {
    stop
    start
}

case "\$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: \$0 {start|stop|restart}"
    exit 1
esac

exit \$?
EOF
    chmod +x ${LXC_ROOT_FS}/etc/init.d/S61HMServer
    
    
    info "Homematic-IP interface was removed, please restart CCU-LXC Container"
    exit
}
