#!/bin/bash
#
# Homematic IP
# 

description="Homematic IP Unterstützung"


_module_install()
{
    echo "noch nicht fertig"
    exit


apt-get install subversion bc gcc-4.7

# aktuelle Kernel Headers runterladen
/opt/YAHM/share/tools/rpi-headers

# Ordner anlegen
mkdir /usr/share/eq3/OCCU
cd /usr/share/eq3/OCCU

# ab git 2.9 koennen wir auch teile auschecken
#git init
#git remote add origin https://github.com/eq-3/occu.git
#git config core.sparsecheckout true
#echo "KernelDrivers/*" >> .git/info/sparse-checkout
#git pull --depth=1 origin master

# nehmen stattdessen svn :D
svn export https://github.com/eq-3/occu/trunk/KernelDrivers

# Makedatei anlegen
cat > "/usr/share/eq3/OCCU/KernelDrivers/Makefile" <<EOF
obj-m	+= eq3_char_loop.c

 
all:
	make -C /lib/modules/\$(shell uname -r)/build M=\$(PWD) modules
 
clean:
	make -C /lib/modules/\$(shell uname -r)/build M=\$(PWD) clean

EOF

# AKtuelle Konfig vorberieten
modprobe configs
# Ins Build verzeichniss wechseln
cd /lib/modules/$(uname -r)/build
gzip -dc /proc/config.gz > .config
# Vorbereitung
make oldconfig


# Modul bauen
cd /usr/share/eq3/OCCU/KernelDrivers/
make clean
insmod eq3_char_loop.ko
}

_module_remove()
{
    check_install_deb "xmlstarlet" 

    progress "Removing HmIP-RF Interface"
    if [ ! -f "${LXC_ROOT_FS}/usr/local/etc/config/InterfacesList.xml" ]
    then
        die "InterfacesList.xml can not be found, please start ${LXCNAME} first"
    fi

    cd ${LXC_ROOT_FS}/usr/local/etc/config/
    xmlstarlet ed -d "/interfaces/ipc[name='HmIP-RF']" InterfacesList.xml > InterfacesList.xml.new
    mv InterfacesList.xml InterfacesList.xml.bak
    mv InterfacesList.xml.new InterfacesList.xml

    cd ${LXC_ROOT_FS}/etc/config_templates/
    xmlstarlet ed -d "/interfaces/ipc[name='HmIP-RF']" InterfacesList.xml > InterfacesList.xml.new
    mv InterfacesList.xml InterfacesList.xml.bak
    mv InterfacesList.xml.new InterfacesList.xml

    info "Homematic-IP interface was removed, please restart CCU-LXC Container"
    exit
}
