#!/bin/bash
#
# Programme drucken
# thkl 2016
# see https://www.homematic-inside.de/software/download/item/webuiprint-addon

description="Installiert das Programme Drucken Plugin"
PATHWWW=$LXC_ROOT_FS/www

_module_install()
{

SCGISTRING="setFooter(s);"
RCGISTRING="setFooter(s); var scriptpp = document.createElement(\\\\\"script\\\\\"); scriptpp.type = \\\\\"text/javascript\\\\\"; scriptpp.src = \\\\\"/addons/script/functions.js\\\\\"; \\\\\$(\\\\\"body\\\\\").appendChild(scriptpp);"

SCGISTRINGZWO="<td align='center' valign='middle'><div class='FooterButton' onclick='CollectData_SaveProfileSettings(0);'>\\\\\${footerBtnOk}</div></td>\\\\\";"
RCGISTRINGZWO="<td align='center' valign='middle'><div class='FooterButton' onclick='CollectData_SaveProfileSettings(0);'>\\\\\${footerBtnOk}</div></td><td align='center' valign='middle'><div class='FooterButton' onclick='PrintPage();'>Drucken</div></td>\\\\\";"

SDEVPARACGI="<td align='center' valign='middle'><div class='FooterButton' onclick='CloseDeviceParameters();'>\\\\\"+translateKey('footerBtnCancel')+\\\\\"</div></td>\\\\\";"
RDEVPARACGI="<td align='center' valign='middle'><div class='FooterButton' onclick='CloseDeviceParameters();'>\\\\\"+translateKey('footerBtnCancel')+\\\\\"</div></td><td align='center' valign='middle'><div class='FooterButton' onclick='PrintDevPara();'>Drucken</div></td>\\\\\";"

SPROGLISTSTRING="<td align='center' valign='middle'><div class='FooterButton CLASS04906' onclick='new HMScriptExecutor();' >\"+translateKey('footerBtnTestScript')+ \"</div></td>"
RPROGLISTSTRING="<td align='center' valign='middle'><div class='FooterButton CLASS04906' onclick='new HMScriptExecutor();' >\"+translateKey('footerBtnTestScript')+ \"</div></td><td align='center' valign='middle'><div class='FooterButton CLASS04905' onclick='PrintAllPrograms();'>alle Programme<br>drucken</div></td><td align='center' valign='middle'><div class='FooterButton CLASS04905' onclick='PrintAllSysPrograms();'>alle Programme inkl. <br>Systeminterne drucken</div></td>"

SSTRINGZWO="setFooter(s);"
RSTRINGZWO="setFooter(s); var scriptpp = document.createElement(\"script\"); scriptpp.type = \"text/javascript\"; scriptpp.src = \"/addons/script/functions.js\"; \$(\"body\").appendChild(scriptpp);"

SSTRING="<td align='center' valign='middle'><div class='FooterButton CLASS04801' onclick='new HMScriptExecutor();'>\${footerBtnTestScript}</div></td>"
RSTRING="<td align='center' valign='middle'><div class='FooterButton CLASS04801' onclick='new HMScriptExecutor();'>\${footerBtnTestScript}</div></td><td align='center' valign='middle'><div class='FooterButton' onclick='PrintPage();'>Drucken</div></td>"

progress "Fetching Knowledge"
mkdir -p $YAHM_TMP

tmpdest="${YAHM_TMP}/pp.tar.gz"
tmppath="${YAHM_TMP}/pp"
mkdir $tmppath

addonurl="https://raw.githubusercontent.com/thkl/YAHM/master/programmedrucken-CCU2.tar.gz"
  wget -q --tries=3 --retry-connrefused  -O $tmpdest $addonurl
    if [ ! -f "$tmpdest" ] 
    then
        die "ERROR: Can not download Addon. Are you connected to the internet?"
    fi

progress "Moving ..."
tar -xzf $tmpdest -C $tmppath



#save original files
progress "Saving original Files"
cp $PATHWWW/config/ic_deviceparameters.cgi $PATHWWW/config/ic_deviceparameters.cgi_org
cp $PATHWWW/config/ic_setprofiles.cgi $PATHWWW/config/ic_setprofiles.cgi_org
cp $PATHWWW/rega/pages/tabs/admin/views/programlist.htm $PATHWWW/rega/pages/tabs/admin/views/programlist.org1
cp $PATHWWW/rega/pages/tabs/admin/views/programs.htm $PATHWWW/rega/pages/tabs/admin/views/programs.org1


#perform changes
progress "Performing some Changes"
 sed -e "s|$SCGISTRING|$RCGISTRING|g" "$PATHWWW/config/ic_deviceparameters.cgi_org" > "$PATHWWW/config/ic_deviceparameters.cgi_tmp"
 sed -e "s|$SDEVPARACGI|$RDEVPARACGI|g" "$PATHWWW/config/ic_deviceparameters.cgi_tmp" > "$PATHWWW/config/ic_deviceparameters.cgi"

 sed -e "s|$SCGISTRING|$RCGISTRING|g" "$PATHWWW/config/ic_setprofiles.cgi_org" > "$PATHWWW/config/ic_setprofiles.cgi_tmp"
 sed -e "s|$SCGISTRINGZWO|$RCGISTRINGZWO|g" "$PATHWWW/config/ic_setprofiles.cgi_tmp" > "$PATHWWW/config/ic_setprofiles.cgi"
	     
 sed -e "s|$SPROGLISTSTRING|$RPROGLISTSTRING|g" "$PATHWWW/rega/pages/tabs/admin/views/programlist.org1" > "$PATHWWW/rega/pages/tabs/admin/views/programlist.htm_tmp"
 sed -e "s|$SSTRINGZWO|$RSTRINGZWO|g" "$PATHWWW/rega/pages/tabs/admin/views/programlist.htm_tmp" > "$PATHWWW/rega/pages/tabs/admin/views/programlist.htm"

 sed -e "s|$SSTRING|$RSTRING|g" "$PATHWWW/rega/pages/tabs/admin/views/programs.org1" > "$PATHWWW/rega/pages/tabs/admin/views/programs.htm_tmp"
 sed -e "s|$SSTRINGZWO|$RSTRINGZWO|g" "$PATHWWW/rega/pages/tabs/admin/views/programs.htm_tmp" > "$PATHWWW/rega/pages/tabs/admin/views/programs.htm"
 chmod 755 $PATHWWW/rega/pages/tabs/admin/views/programs.htm


#copy stuff

progress "Copy some stuff "
cp $tmppath/script/PrintPrograms.fn $PATHWWW/rega/esp/PrintPrograms.fn
chmod 755 $PATHWWW/rega/esp/PrintPrograms.fn     
cp $tmppath/script/PrintProgram.htm $PATHWWW/rega/esp/PrintProgram.htm
chmod 755 $PATHWWW/rega/esp/PrintProgram.htm   
mkdir $LXC_ROOT_FS/usr/local/etc/config/addons/www/script
cp $tmppath/script/* $LXC_ROOT_FS/usr/local/etc/config/addons/www/script/

progress "Cleaning"
rm -R $tmppath
rm $tmpdest

}

_module_remove()
{
  progress "Removing ..."
  rm $PATHWWW/rega/esp/PrintPrograms.fn
  rm $PATHWWW/rega/esp/PrintProgram.htm
  rm -R $LXC_ROOT_FS/usr/local/etc/config/addons/www/script/
  progress "Restoring old files"
  
  mv $PATHWWW/config/ic_deviceparameters.cgi_org $PATHWWW/config/ic_deviceparameters.cgi
  mv $PATHWWW/config/ic_setprofiles.cgi_org $PATHWWW/config/ic_setprofiles.cgi
  mv $PATHWWW/rega/pages/tabs/admin/views/programlist.org1 $PATHWWW/rega/pages/tabs/admin/views/programlist.htm
  mv $PATHWWW/rega/pages/tabs/admin/views/programs.org1 $PATHWWW/rega/pages/tabs/admin/views/programs.htm

}