#!/bin/bash
#
# New beta Regahss service (without variable limit)
#

description="Installiert aktelle Beta Version von ReGaHss für die CCU2 FW"

_module_install()
{
    rega_beta_url="https://github.com/eq-3/occu/raw/master/CCU2/packages-eQ-3/WebUI-Beta/bin/ReGaHss"

    if [ ! -f ${LXC_ROOT_FS}/bin/ReGaHss.orig ]
    then
        progress "Backup old original ReGaHss file"
        cd ${LXC_ROOT_FS}/bin
        mv ReGaHss ReGaHss.orig
    fi

    progress "Removing ReGaHss file"
    rm -rf ${LXC_ROOT_FS}/bin/ReGaHss

    progress "Downloading ReGaHss Beta file"
    wget $QUIET -O ${LXC_ROOT_FS}/bin/ReGaHss ${rega_beta_url}
    chmod +x ${LXC_ROOT_FS}/bin/ReGaHss

    progress "Restarting ReGaHss service"
    lxc-attach -n ${LXCNAME} -- /etc/init.d/S70ReGaHss restart
}

module_remove()
{
    if [ -f ${LXC_ROOT_FS}/bin/ReGaHss.orig ]
    then
        progress "Restore old original ReGaHss file"
        cd ${LXC_ROOT_FS}/bin
        mv ReGaHss.orig  ReGaHss
    fi

    progress "Restarting ReGaHss service"
    lxc-attach -n ${LXCNAME} -- /etc/init.d/S70ReGaHss restart
}