#!/bin/bash
#
# Template for new Modules
# 

description="Just a template for new module"

_module_install()
{
    echo        "Container Name is: ${LXCNAME}"
    echo        "Module Name is: ${MODULE}"
    echo        "Container ROOT is: ${LXC_ROOT}"
    echo        "Container ROOT_FS is: ${LXC_ROOT_FS}"

    if [ $IS_FORCE -eq 1 ]
    then
        info "Entering force mode"
    fi

    if [ $IS_VERBOSE -eq 1 ]
    then
        info "Verbose is selected, QUIET=${QUIET} VERBOSE=${VERBOSE}"
    fi
    
    info        "template info message"
    progress    "template progress message"
    die         "template exit"
}

_module_remove()
{
    echo "template remove"
}

